services:
  zenoh-mqtt-r1:
     image: eclipse/zenoh:1.0.0
     command: -c /config.json5
     environment:
     - ZENOH_BACKEND_FS_ROOT=/opt/zenoh
     volumes:
      - ./zenoh:/root/.zenoh
      - ./storage1:/opt/zenoh
      - ./config-r1.json5:/config.json5
     networks:
      app_net:
        ipv4_address: 172.16.238.11
     ports:
      - 1883:1883
      - 7447:7447
      - 7447:7447/udp
      - 8000:8000
  zenoh-mqtt-r2:
     image: eclipse/zenoh:1.0.0
     command: -c /config.json5
     environment:
     - ZENOH_BACKEND_FS_ROOT=/opt/zenoh
     volumes:
      - ./zenoh:/root/.zenoh
      - ./storage2:/opt/zenoh
      - ./config-r2.json5:/config.json5
     networks:
      app_net:
        ipv4_address: 172.16.238.12
     ports:
      - 1884:1883
      - 7448:7447
      - 7448:7447/udp
      - 8001:8000
  mqtt:
     image: emqx/nanomq:latest
     volumes:
       - ./nanomq.conf:/etc/nanomq.conf
     networks:
      app_net:
        ipv4_address: 172.16.238.13
     ports:
       - "2883:1883"
       - "8083:8083"
       - "8883:8883"
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  